In [3]:
import numpy as np

class SimpleNeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size, learning_rate=0.2):
        # Initialize weights (CHANGED)
        self.W1 = np.array([
            [0.2, -0.4],
            [0.6,  0.3],
            [-0.1, 0.5]
        ])
        print(f"Initialized W1:\n{self.W1}")

        self.W2 = np.array([
            [0.4],
            [-0.7]
        ])
        print(f"Initialized W2:\n{self.W2}")

        # Initialize biases (CHANGED)
        self.b1 = np.array([[0.2, 0.05]])
        print(f"Initialized b1:\n{self.b1}")

        self.b2 = np.array([[0.1]])
        print(f"Initialized b2:\n{self.b2}")

        self.lr = learning_rate
        print(f"Learning Rate: {self.lr}")

    # Sigmoid activation function
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    # Derivative of sigmoid
    def sigmoid_derivative(self, x):
        return x * (1 - x)

    # Forward propagation
    def forward(self, x):
        self.x = x

        self.hidden_raw = np.dot(self.x, self.W1) + self.b1
        self.hidden_output = self.sigmoid(self.hidden_raw)

        self.output_raw = np.dot(self.hidden_output, self.W2) + self.b2
        self.output = self.sigmoid(self.output_raw)

        print(f"Forward Pass Output:\n{self.output}")
        return self.output

    # Mean Squared Error loss
    def compute_loss(self, y_true, y_pred):
        loss = np.mean((y_true - y_pred) ** 2)
        print(f"Calculated Loss: {loss}")
        return loss

    # Backward propagation
    def backward(self, y_true):
        # Output layer error
        error_output = y_true - self.output
        delta_output = error_output * self.sigmoid_derivative(self.output)

        # Hidden layer error
        error_hidden = np.dot(delta_output, self.W2.T)
        delta_hidden = error_hidden * self.sigmoid_derivative(self.hidden_output)

        # Update weights and biases
        self.W2 += self.lr * np.dot(self.hidden_output.T, delta_output)
        self.b2 += self.lr * delta_output

        self.W1 += self.lr * np.dot(self.x.T, delta_hidden)
        self.b1 += self.lr * delta_hidden

    # Training step
    def train(self, x, y):
        y_pred = self.forward(x)
        loss = self.compute_loss(y, y_pred)
        self.backward(y)
        print(f"Training Step Loss: {loss}")
        return loss


In [2]:
# Create an instance of the neural network
# Input size: 3 (e.g., 3 features)
# Hidden size: 2
# Output size: 1
# Learning rate: 0.1 (default)
neural_network = SimpleNeuralNetwork(input_size=3, hidden_size=2, output_size=1)

# Define some sample input (x) and target output (y) data
x = np.array([[0.1, 0.2, 0.3]])
y = np.array([[0.8]])

print(f"\nInput X:\n{x}")
print(f"Target Y:\n{y}")

# Train the network for a few iterations
print("\n--- Starting Training ---")
for i in range(5): # Train for 5 epochs
    loss = neural_network.train(x, y)
    print(f"Epoch {i+1}, Loss: {loss}")

print("\n--- Training Complete ---")

# After training, you can make a prediction
final_prediction = neural_network.forward(x)
print(f"\nFinal Prediction after training:\n{final_prediction}")

Initialized W1:
[[ 0.2 -0.4]
 [ 0.6  0.3]
 [-0.1  0.5]]
Initialized W2:
[[ 0.4]
 [-0.7]]
Initialized b1:
[[0.2  0.05]]
Initialized b2:
[[0.1]]
Learning Rate: 0.2

Input X:
[[0.1 0.2 0.3]]
Target Y:
[[0.8]]

--- Starting Training ---
Forward Pass Output:
[[0.48560614]]
Calculated Loss: 0.09884350035595665
Training Step Loss: 0.09884350035595665
Epoch 1, Loss: 0.09884350035595665
Forward Pass Output:
[[0.49222059]]
Calculated Loss: 0.09472816354918756
Training Step Loss: 0.09472816354918756
Epoch 2, Loss: 0.09472816354918756
Forward Pass Output:
[[0.49869977]]
Calculated Loss: 0.09078183000142766
Training Step Loss: 0.09078183000142766
Epoch 3, Loss: 0.09078183000142766
Forward Pass Output:
[[0.50504216]]
Calculated Loss: 0.08700012605621668
Training Step Loss: 0.08700012605621668
Epoch 4, Loss: 0.08700012605621668
Forward Pass Output:
[[0.51124683]]
Calculated Loss: 0.08337839257793442
Training Step Loss: 0.08337839257793442
Epoch 5, Loss: 0.08337839257793442

--- Training Complete ---
